### PR TITLE
Bug/fix cards categorised by region

### PR DESCRIPTION
**Pull request by Jchinonso**
#### What does this PR do?
- Categorize cards by region
#### Description of Task to be completed?
- User should be able to get cards based of the input location
#### How should this be manually tested?
- Nill
#### Any background context you want to provide?
- Nill
#### What are the relevant pivotal tracker stories?
- #148328333
#### Screenshots (if appropriate)
- 
image
image

#### Questions:

### CODE REVIEW

**Comment by temilaj** [comment]
You don't seem to be using the right commit message convention. why is that?

**Comment by Jchinonso** [comment]
Tried to squash into few commits, but most of the commit seen where stacked on my existing commit after i pull from staging..

**Comment by temilaj** [comment]
That doesn't explain your commit message conventions

**Comment by Jchinonso** [comment]
I initially raised a pull request to see how many commit messages it has so i literally sent that last commit message with an intent to squash after..

**Comment by temilaj** [comment]
Alright. Let's try to add more regions

**Pull request closed without merging**
